### ISSUE TITLE
3d files for cpap

### ISSUE THREAD

**Issue by trackhacs** [bsilly1/blv-mgn-cube-with-cpap#1]
was hoping to find the 3d files to adapt cpap to my BLV here. any hint where to find someting?

**Comment by bsilly1** [comment]
i can send you what i used, but i modified the eva, and a setup from someone else to meet my needs. i am running the nf sunrise with volcano on the blv metal kit. I modified the files with ideamaker and sliced everything with orcaslicer using tree supports where needed. I will try to send or upload to here this evening

**Comment by bsilly1** [comment]
![Screenshot_20230406-141553.png](https://user-images.githubusercontent.com/114705159/230462408-4280aacf-1150-4678-9769-26bfc1ecec54.png)

![Screenshot_20230406-141444.png](https://user-images.githubusercontent.com/114705159/230462457-cb67339d-48e1-44f9-a44d-41128b7db31a.png)

**Comment by bsilly1** [comment]
![Screenshot_20230406-141444.png](https://user-images.githubusercontent.com/114705159/230462728-434e8619-bcfd-4e72-bf7c-818cd1c232b0.png)

![Screenshot_20230406-141451.png](https://user-images.githubusercontent.com/114705159/230462762-eccfcdd1-45d6-44e7-84f8-e1021f94865a.png)

**Comment by trackhacs** [comment]
looks good. kinda on the same point now, and would love to try it. not using volcano now (CHT seems so much better)- so might be a little bit low - but maybe the back plate might work.

**Comment by bsilly1** [comment]
you could probably take the back plate im using and duplicate it and possibly merge together to lower your sunrise down. i dont believe you will be able to raise the actual duct any. im running the volcano with a clone CHT nozzle currently seems good. the cpap blower setup was the game changer for cooling for me!

**Comment by trackhacs** [comment]
what maximum flow rate you are running?

is the interconnect between bottom nozzles and back plane interchangeable with EVA components ? maybe I can just use different nozzles from here.

CPAP all here - just adapter is missing - and hoped to find some ready part as adapter  - without needing whole easter holidays to construct my own adapter :)

also have an biqu h2 here, same game though.  :\

**Comment by bsilly1** [comment]
i merged the backplate and the back ducting into one so i could make it as narrow as possible to not lose y movement. Steffen stretched the actual fan duct out so it would reach for the nf sunrise.  the backplate was a mixture of Steffen's blv metal kit backplate and the eva cpap duct. i went a different route than the eva superpinda mount so that it would mount directly to the sunrise and be as close to the nozzle as i could. i will post/send all the stl's for my setup hopefully this evening. at the very least it will get you a good starting point hopefully.

**Comment by bsilly1** [comment]
here you go i have uploaded them here: https://github.com/bsilly1/blv-mgn-cube-with-cpap/tree/main/cpap%20stl's

**Comment by bsilly1** [comment]
feel free to let me know if there are issues with those. i am closing this.
